### ISSUE TITLE
Half column value support

### ISSUE THREAD

**Issue by justinholtweb** [lucasgruwez/waffle-grid#13]
It would be awesome to have Waffle support column, pushes, and pull values as **col-3.5-of-12** or **push-2.5-of-12** or **pull-3.5-of-12**. Currently entering values with remainders seems to breaking those column sizes.

**Comment by RoterNagel** [comment]
Hey Justin,
You can't use a dot in a class name for css. If your use waffle-grid within your SCSS/SASS you can customize your grid to fit your needs: https://github.com/lucasgruwez/waffle-grid/wiki/Using-the-grid#customizing-the-grid

Just add a 24 to your grid-columns and change your class from **push-2.5-of-12** to **push-5-of-24**
Hope this helps.

**Comment by lucasgruwez** [comment]
@RoterNagel, 

Thanks for answering @justinholtweb's question. Half column sizes aren't available because it is just easier to double the number of columns and to use (as you said) `push-5-of-24` instead of `.push-2.5-of-12`, or because we can't use dots in CSS name classes, `push-5-of-24` instead of `.push-3-5-of-12`.

Lucas

**Comment by justinholtweb** [comment]
OMG thanks, I don't know how I overlooked the dots in classnames! The method to double the column sizes is perfect solution.

BTW Waffle is awesome!

**Comment by lucasgruwez** [comment]
You're welcome!!
