### ISSUE TITLE
Question on grid container

### ISSUE THREAD

**Issue by jackmcpickle** [lucasgruwez/waffle-grid#9]
Hi @lucasgruwez, 

just a question on the `.grid` class on why the need for the `display: flex;` and `flex-direction: column;`?
Flex columns rely on height being set to utilise some of the other flex properties like `justify-content`, etc. 

The main properties of the `.grid` class seem to be acting more like a container then a grid wrapper. 
Seems like more of a special case - as your example on the site doesn't require it. 

Just curious as a fellow flex framework dev. 😁

**Comment by lucasgruwez** [comment]
Hi @jackmcpickle 

I am a bit confused by your question... I do not fully get what you mean in your first paragraph, but let me try and explain my logic behind the properties set on the `.grid` class:

I am in this grid using the `.grid` class as both the grid wrapper and a container to center the grid. This removes the need for extra markup that I usually have.
```html
<div class="container">
  <div class="grid">
    ...
  </div>
</div>
```

I will add a `.container` class that will only center the content without the flex properties, and I will also add the possibility to make the grid full width (it will probably be something like `.grid.full-width`) in version 1.3.2.

I am now currently traveling, and don't have my computer with me (this here was written from my tablet), so v1.3.2 will probably be released Friday or Saturday.

Thanks for your help and participation in this project! 🙂

Lucas

**Comment by jackmcpickle** [comment]
Thanks for the prompt response. Hopefull this pen should illustrate my point better. http://codepen.io/jackmcpickle/pen/EWEMJe

By commenting out the flex properties on the grid class I achieve the same result.

**Comment by lucasgruwez** [comment]
The reason why it is set to `display: flex;` and `flex-direction: column;` is actually for a couple of features I am currently working on. I think it is best that we keep it that way even without the additional features, in case there are some unwanted effects caused by removing those properties (or adding them later).

If you want to use waffle-grid by removing those properties, feel free to do so! And if you ever make a website with it, make sure to send me a link by email (gruwez.lucas@gmail.com) so that I can check out what you made, and I might add it to an examples section on the website.

Lucas

**Comment by lucasgruwez** [comment]
I added the helper classes even though it wasn't what you meant in the original issue, I think it might come in handy to some other people...

Thanks again for your involvement in this project!

Lucas
